# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-redirect-from

# Site settings
title: "Data Transition Blog"
description: > # this means to ignore newlines until "email:"
   Faire société à l'ère numérique

email: a-mail@mail.mail
#blog logo
logo: "/assets/images/dt_logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg" 
#cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Data Transition'
author: 'Data Transition Team'
author_image: "/assets/images/dt_logo.png"

paginate: 5

url: "https://blog.datatransition.net" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: "@DT_privacy"

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon: "twitter"
    url: "https://twitter.com/DT_privacy"
    desc: "Follow me on twitter"
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/dirkfabisch
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

